name: Builds vanilla armbian image, for debugging

on:
  workflow_dispatch:
    inputs:
      armbian-board:
        type: choice
        description: 'Board'
        default: 'orangepizero3'
        options:
        - aml-a311d-cc
        - aml-s905d3-cc
        - armsom-aim7-io
        - armsom-cm5-io
        - armsom-sige1
        - armsom-sige5
        - armsom-sige7
        - armsom-w3
        - avaota-a1
        - bananapi
        - bananapicm4io
        - bananapif3
        - bananapim1plus
        - bananapim2plus
        - bananapim2pro
        - bananapim2s
        - bananapim2ultra
        - bananapim2zero
        - bananapim3
        - bananapim4zero
        - bananapim5
        - bananapim64
        - bananapim7
        - bananapipro
        - bananapir2
        - bananapir2pro
        - beaglev
        - bigtreetech-cb1
        - cherryba-m1
        - clearfogbase
        - clearfogpro
        - clockworkpi-a06
        - coolpi-cm5
        - cubieboard
        - cubieboard2
        - cubieboard4
        - cubietruck
        - cubox-i
        - fine3399
        - firefly-itx-3588j
        - firefly-rk3399
        - fxblox-rk1
        - gateway-gz80x
        - helios4
        - helios64
        - hikey960
        - hinlink-h28k
        - hinlink-h66k
        - hinlink-h68k
        - hinlink-h88k
        - hinlink-hnas
        - hinlink-ht2
        - indiedroid-nova
        - inovato-quadra
        - jethubj100
        - jethubj200
        - jethubj80
        - jetson-nano
        - khadas-edge
        - khadas-edge2
        - khadas-vim1
        - khadas-vim1s
        - khadas-vim2
        - khadas-vim3
        - khadas-vim3l
        - khadas-vim4
        - lafrite
        - lckfb-taishanpi
        - leez-p710
        - lepotato
        - lime-a33
        - lime-a64
        - lime
        - lime2
        - longanpi-4b
        - lubancat2
        - macchiatobin-doubleshot
        - mangopi-m28k
        - mba8mpxl-ras314
        - mba8mpxl
        - mekotronics-r58-minipc
        - mekotronics-r58x-4g
        - mekotronics-r58x-pro
        - mekotronics-r58x
        - melea1000
        - mixtile-blade3
        - mk808c
        - nanopc-cm3588-nas
        - nanopct4
        - nanopct6
        - nanopi-r1
        - nanopi-r1s-h5
        - nanopi-r2c
        - nanopi-r2s
        - nanopi-r4s
        - nanopi-r4se
        - nanopi-r5c
        - nanopi-r5s
        - nanopi-r6c
        - nanopi-r6s
        - nanopia64
        - nanopiair
        - nanopiduo
        - nanopiduo2
        - nanopik1plus
        - nanopik2-s905
        - nanopim4
        - nanopim4v2
        - nanopineo
        - nanopineo2
        - nanopineo2black
        - nanopineo3
        - nanopineo4
        - nanopineocore2
        - nanopineoplus2
        - odroidc1
        - odroidc2
        - odroidc4
        - odroidhc4
        - odroidm1
        - odroidn2
        - odroidn2l
        - odroidxu4
        - olimex-a20-olinuxino-micro
        - olimex-teres-a64
        - olinux-som-a13
        - onecloud
        - orangepi-r1
        - orangepi-r1plus-lts
        - orangepi-r1plus
        - orangepi-rk3399
        - orangepi2
        - orangepi3-lts
        - orangepi3
        - orangepi3b
        - orangepi4-lts
        - orangepi4
        - orangepi5-plus
        - orangepi5
        - orangepi5pro
        - orangepilite
        - orangepilite2
        - orangepione
        - orangepioneplus
        - orangepipc
        - orangepipc2
        - orangepipcplus
        - orangepiplus
        - orangepiplus2e
        - orangepiprime
        - orangepiwin
        - orangepizero
        - orangepizero2
        - orangepizero2w
        - orangepizero3
        - orangepizeroplus
        - orangepizeroplus2-h3
        - orangepizeroplus2-h5
        - panther-x2
        - pcduino3
        - phytiumpi
        - pine64
        - pine64so
        - pinebook-a64
        - pinebook-pro
        - pinecube
        - pineh64-b
        - pineh64
        - qemu-uboot-arm64
        - qemu-uboot-x86
        - qemu-uefi-x86
        - quartz64a
        - quartz64b
        - radxa-e20c
        - radxa-e25
        - radxa-e52c
        - radxa-zero
        - radxa-zero2
        - radxa-zero3
        - recore
        - renegade
        - retro-lite-cm5
        - rk3328-heltec
        - roc-rk3399-pc
        - rock-3a
        - rock-3c
        - rock-4se
        - rock-5-cmio
        - rock-5-itx
        - rock-5a
        - rock-5b
        - rock-5c
        - rock-s0
        - rock64
        - rockpi-4a
        - rockpi-4b
        - rockpi-4bplus
        - rockpi-4c
        - rockpi-4cplus
        - rockpi-e
        - rockpi-n10
        - rockpi-s
        - rockpro64
        - rpi4b
        - rpi5b
        - sakurapi-rk3308b
        - sk-am62b
        - sk-am64b
        - sk-am68
        - sk-tda4vm
        - star64
        - station-m1
        - station-m2
        - station-m3
        - station-p1
        - station-p2
        - sweet-potato
        - thinkpad-x13s
        - tinker-edge-r
        - tinkerboard-2
        - tinkerboard
        - tritium-h3
        - tritium-h5
        - turing-rk1
        - udoo
        - uefi-arm64
        - uefi-riscv64
        - uefi-x86
        - unleashed
        - unmatched
        - visionfive
        - visionfive2
        - wdk2023
        - wsl2-arm64
        - wsl2-x86
        - xiaobao-nas
        - xiaomi-elish
        - xiaomi-umi
        - youyeetoo-r1-v3
        - zeropi

jobs:
  build-armbian:
    runs-on: ubuntu-latest
    name: Build Armbian
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          submodules: 'true'
          
      - name: Build Armbian
        run: |
          git clone --depth=1 --branch=main https://github.com/armbian/build
          ./build/compile.sh \
          BOARD=${{ github.event.inputs.armbian-board }} \
          BRANCH=current \
          RELEASE=noble \
          BUILD_MINIMAL=yes \
          KERNEL_CONFIGURE=no\

      - name: Upload Armbian image
        uses: actions/upload-artifact@v4
        with:
          name: Armbian_firmware
          path: build/output/images/*
